In [5]:
class Employee: 

  def count_emp(self,employee,fullemp): 
        print("The total Number of Employees(employee+Fulltime employee):",len(employee+fullemp)) #counting number of employees.
      
  def __init__(self,name,family,salary,department): #constructor for name,family,salary and Department.
        self.name =name 
        self.family =family 
        self.salary=salary 
        self.department=department 
        
  def avg_salary(self,employee,fullemp):  #function for calculating the average salaryof all employees.
       sum=0 
       for i in employee: 
           sum=sum+i.salary 
       for i in fullemp: 
            sum=sum+i.salary 
       print("the average salary of the all the Employees(employee+Fulltime employee):",sum/2) 
        
class Fulltime_Employee(Employee): 
    pass 
n=int(input("enter number of employees")) 
pe=[] 
for i in range(0,n):  #using for() loop,take the input dynamically.
    na=input("enter name") 
    f=int(input("enter how many family members")) 
    s=int(input("enter salary")) 
    d=input("enter department") 
    obj=Employee(na,f,s,d) 
    pe.append(obj) 
full=int(input("enter Full time employees")) 
fe=[] 
for i in range(0,full): 
    na=input("enter name") 
    f=int(input("enter how many family members")) 
    s=int(input("enter salary")) 
    d=input("enter department") 
    obj=Fulltime_Employee(na,f,s,d) 
    fe.append(obj) 
    
result=Fulltime_Employee(na,f,s,d)  
result.count_emp(pe,fe) #function call
result.avg_salary(pe,fe) #function call

enter number of employees 3
enter name Raj
enter how many family members 4
enter salary 3000
enter department EEE
enter name Varun
enter how many family members 4
enter salary 2000
enter department DEEE
enter name Pranay
enter how many family members 5
enter salary 3500
enter department MECH
enter Full time employees 1
enter name Hanoop
enter how many family members 4
enter salary 30000
enter department CSE


The total Number of Employees(employee+Fulltime employee): 4
the average salary of the all the Employees(employee+Fulltime employee): 19250.0


In [8]:
import numpy as np #import numpy
ar = np.arange(1,21,dtype=float) #vector of size 1-20
print("Vector :",ar) 
ar=ar.reshape(4,5) #use reshape() to reshape the array into 4*5 
print("Then reshape the array to 4 by 5:",ar) 
def replace(ar): 
    var=ar 
    var[:,np.argmax(ar, axis=1)] = 0 
    return var 
result= replace(ar) 
print("replace the max in each row by 0 (axis=1):",result)

Vector : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
Then reshape the array to 4 by 5: [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]
replace the max in each row by 0 (axis=1): [[ 1.  2.  3.  4.  0.]
 [ 6.  7.  8.  9.  0.]
 [11. 12. 13. 14.  0.]
 [16. 17. 18. 19.  0.]]
